### ISSUE TITLE
[Bug]: Patch for “Modern Stagger Lock” has no motion in pandora.

### ISSUE THREAD

**Issue by EIKICHIONI** [Monitor144hz/Pandora-Behaviour-Engine-Plus#109]
Patch for “Modern Stagger Lock” not working in pandora. In pandora versions 1.0.0~1.1.6, the patch "Modern Stagger Lock" has a bug that does not take effect. Not sure about other versions.

**Comment by Monitor144hz** [comment]
[Read this](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development#bug-reports)

**Comment by neeeetuo** [comment]
Confirm that it does not work in version 1.15.

**Comment by Monitor144hz** [comment]
@EIKICHIONI @neeeetuo what exactly is the bug that with Modern Stagger Lock? Does it not work at all?

**Comment by elbadcode** [comment]
Previously could not generate patch with this mod at all, pre version 1.0 but also had issues patching it with nemesis so probably incompatibility. Patches correctly with latest version of pandora and seems to be working fine on 1.5.97. Also did not cause issues in 1.6.64 but unsure if it worked correctly due to dll version incompatibility. Unsure if latest pandora update fixed this or if it was a mod issue

**Comment by EIKICHIONI** [comment]
@Monitor144hz It didn't knock back or fly away, it would just repeat the action on the spot. “Modern Stagger Lock”

**Comment by EIKICHIONI** [comment]
@Monitor144hz 
[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14396371/Engine.log)

**Comment by jackson8541** [comment]
+1

**Comment by Monitor144hz** [comment]
@EIKICHIONI @jackson8541 do you have AMR installed? It is a requirement for the mod

**Comment by EIKICHIONI** [comment]
@Monitor144hz Yes,i am installed.but still is.

**Comment by Monitor144hz** [comment]
> Tried version 1.4.3 today and the bug seems to have disappeared.
