### ISSUE TITLE
Pandora setup

### ISSUE THREAD

**Issue by nopse0** [Monitor144hz/Pandora-Behaviour-Engine-Plus#131]
I have a question about the general Pandora setup.

I am using "Pandora.XPMSE.Patch.v1.1.3.Universal" patch, and am trying to recompile zadBQ001.psc from Devious Devices 5.2-NG.

The XMPSE contains two scripts (without sources, why?), FNIS.pex and FNIS_aa.pex. which are indirectly referenced via SexLab Framework. I decompiled the scripts with Champollion, but FNIS_aa.psc has refereces to nemesis_aa.

Am I right, assuming that you took the FNIS scripts and fnis.esp from Nemesis ? Do I have to install the Nemesis .pex scripts (and .psc sources if I want to compile something) ? And is this going to work ?

**Comment by Monitor144hz** [comment]
> Am I right, assuming that you took the FNIS scripts and fnis.esp from Nemesis ? Do I have to install the Nemesis .pex scripts (and .psc sources if I want to compile something) ? And is this going to work ?

I don't know what the FNIS scripts are doing exactly and I haven't bothered to check; I left them in there to be better safe than sorry, as Nemesis includes them in the output (and yes, there's no source there). 

From what you found out, I'm guessing Nemesis_AA is for Nemesis Alternate Animations, in which case you can delete the FNIS_AA script safely because a better alternative exists in OAR (and I heavily recommend switching to this if you need dynamic alternate animations instead of papyrus). I wouldn't delete FNIS.pex unless you know exactly what it's doing, which mods need it, and why it's safe to not include.

Regarding whether the engine works or not, you can try it yourself and see. Keep in mind that some FNIS animation types are not directly compatible with Pandora yet though, as seen in the open issue #76.

You can ask me more general questions in the discussion forum, closing this issue here.

**Comment by nopse0** [comment]
Hello, I just wanted to say thanks! Your comments brought me to think about "Do I really need FNIS.pex/FNIS_aa.pex/NEMESIS_aa.pex/etc.?", and the answer is: no. The whole problems arise only from the XPMSE scripts. I cleaned my save file, installed XMPSE Lite +  Immersive Equipment Display, reran Pandora, and everything works fine (and faster then before) now. No T-Poses, SexLab scenes work, everything's fine!
Ps: Didn't saw there's a discussion forum, otherwise I would have aked my question there,
