### ISSUE TITLE
gender specific animations and xpmse weapon style animation do not work

### ISSUE THREAD

**Issue by JustTE97** [Monitor144hz/Pandora-Behaviour-Engine-Plus#149]
I'm not sure if it's a Pandora problem, there's no such problem in FNIS or Nemesis. I'm using v1.2.2-alpha.

**Comment by haydnman** [comment]
Having the same issue, trying to install the walk/run animations from GSposes but it doesn't recognize the animations unlike in FNIS

**Comment by Monitor144hz** [comment]
Pandora does not support gender specific animations because Open Animation Replacer replaces it in terms of functionality. Nor does it support weapon styles as that is succeeded by Immersive Equipment Display to my knowledge. 

I understand this isn't the answer users may want to hear, but as development time and energy is limited, Pandora cannot spend time reinventing the wheel when alternative solutions exist.

**Comment by haydnman** [comment]
Ah, must've been long enough since I've last modded that I hadn't heard about either. Just installed OAR and things are working perfectly now. Thanks for the response - I'm guessing this is something that gets brought up semi-frequently, so I don't mean to beat a dead horse. Appreciate the work you do! I'll definitely be supporting on Patreon when I can.
