### ISSUE TITLE
Where is the .exe file?

### ISSUE THREAD

**Issue by AdeptusXIII** [Monitor144hz/Pandora-Behaviour-Engine-Plus#206]
There's no point in having sources if I have no idea how to compile them...

**Comment by SARDONYX-sard** [comment]
## Requirements
 - [VS Studio 2022](https://visualstudio.microsoft.com/downloads/)
   The dotnet7.0 SDK is required.(This should probably be automatically downloaded when VS Studio is installed.)
   
   Ref: [Install .NET on Windows](https://learn.microsoft.com/en-us/dotnet/core/install/windows?WT.mc_id=dotnet-35129-website&tabs=net80#install-with-windows-package-manager-winget)
 - [git](https://git-scm.com/download/win)
 
   If you are using Windows 11, the winget command is installed by default, so simply execute the following command on cmd.exe or powershell.exe to install.
 
   ```powershell
   winget install --id Git.Git -e --source winget
   ```

## Build

1. First you need to download the source code. (Add the `--recursive` option to download git submodules dependencies in one go as well).

```powershell
git clone --recursive https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus.git
```

  2. You can build here. (if the path to the `dotnet` command is registered in the environment variable)
  INFO: NuGet package dependencies are downloaded automatically.

- Debug(Prioritize short compile time over optimization)

```powershell
dotnet build "./PandoraPlus.sln" --configuration Debug
```

or

- Release(Optimization is performed instead of longer compile time)

```powershell
dotnet build "./PandoraPlus.sln" --configuration Release
```

3. The following directories contain the executable file and its dependencies after build.

```shell
./PandoraPlus/bin/Release(or Debug)/net7.0-windows
```

![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/68905624/9bfe353b-7dd0-4bcf-9bb0-a62b55d6af7d)

## Reference sites




## Related issues

- [Engine not recognizing current .NET](#159)

**Comment by Monitor144hz** [comment]
@AdeptusXIII are you still having issues building the source files or are you just looking for the prebuilt exes?

**Comment by AdeptusXIII** [comment]
I initially wanted to build this, but I had some non-obvious problems with VS.  Then I gave up and couldn't find the prebuilt exe.  After some time I solved the problems with VS.  This is truly the behavior engine I was looking for.  This engine does it all.

**Comment by Monitor144hz** [comment]
for reference next time the prebuilt exe is in the Releases section on the main page
![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/89633536/593fa563-f929-4fbc-9a49-0793d14c716e)
Glad you're enjoying it. let me know if there are any bugs.

**Comment by AdeptusXIII** [comment]
For some reason I'm getting a page loading error.
