### ISSUE TITLE
I dragged and dropped it like a mod and this is what i get v.0.6.1

### ISSUE THREAD

**Issue by DarklyNightly** [Monitor144hz/Pandora-Behaviour-Engine-Plus#21]
![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/75499681/54a2ed43-c238-4bcb-8783-812cf8dfffad)

**Comment by Monitor144hz** [comment]
What mods did you have active? Is this with a specific mod manager? How did you drag and drop it?

**Comment by Monitor144hz** [comment]
The .exe file should be in the Data folder of the Skyrim directory. If it is in another folder you need to move it and all the files alongside it outside to the Data directory. I use MO2 so I cannot provide more detailed help, but it doesn't seem like a bug, just how the mod is packaged.

**Comment by onlyspidey** [comment]
yh now other patches show up but after I press launch it just crashes, could that be due to the large amount of animations I have or something else?

**Comment by elbadcode** [comment]
vortex defaults to using symbolic links to copy your mods into the data folder which basically means the files don't actually move but windows believes they do. Very possible that the program can't handle symbolic links automatically. Vortex has a reversible option to actually move the files into the data folder instead of symlinking. I'd recommend you try switching to that when you run pandora. If it works then symlinks were the issue. If it doesnt work it could be your mods or something else

**Comment by onlyspidey** [comment]
hey sorry got a bit busy with exams but this did not fix it, I even manually copied everything over to the data folder still nothing, even tried MO2 but still the same issue so idk what's wrong anyways I'll keep trying I guess thank you for the help

**Comment by Monitor144hz** [comment]
The exe file and any other files/folders alongside it should be straight in the data folder @onlyspidey 
![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/89633536/e14ad3d0-e1d1-4b30-b481-4303433f054d)

**Comment by onlyspidey** [comment]
yes I tried that but still didn't work, maybe it is somehow vortex messing it up oh well I'll keep experimenting and will let you know if I manage to fix it. thanks for the help
