### ISSUE TITLE
TK Dodge SE/Standalone Has No Motion Displacement (Pandora Will Only Support Motion Data via AMR)

### ISSUE THREAD

**Issue by Monitor144hz** [Monitor144hz/Pandora-Behaviour-Engine-Plus#28]
TK Dodge Standalone includes its own motion data using the vanilla method of animationdatasinglefile. I do not intend to support this method as it is a highly painful process for the author involved when they could just use [Animation Motion Revolution](https://www.nexusmods.com/skyrimspecialedition/mods/50258) which has been around for quite a while and is a stable and easy solution to add displacement to animations.

[Please use a patch or version for TK Dodge RE that supports AMR](https://www.nexusmods.com/skyrimspecialedition/mods/111788), or use another dodge mod. Nemesis also works fine for that.

**Comment by Monitor144hz** [comment]
reopened so that this issue gets more visibility

**Comment by elbadcode** [comment]
Just to add onto this with more specific info from my experience, the latest version on Nexus (0.55-rc3) can patch but animations happen in place unless patching over an existing nemesis output.

However the [version 0.62](https://www.nexusmods.com/skyrimspecialedition/mods/56956?tab=files&file_id=379617) labeled outdated does have motion, I believe through AMR, and has an in-game MCM to set the hotkey. I'm not sure what's outdated about this, perhaps it adds some script lag, but it's actually functional so that's my recommendation. 

Otherwise or in addition if you want two types of dodge, you can use dmco (good for MCO/dxp) or cgo lite (good for vanilla or abr). TUDM has not worked for me for a few months, not sure if it's script issues or Pandora, but that mod is too finicky and can break due to scripts so I'd avoid it anyway

**Comment by Monitor144hz** [comment]
> Someone made a patch for this here fyi
> https://www.nexusmods.com/skyrimspecialedition/mods/111788

updated the post to reflect this, and closing as the patch solves all problems here anyway
