### ISSUE TITLE
Question about SexLab

### ISSUE THREAD

**Issue by Kazyachka** [Monitor144hz/Pandora-Behaviour-Engine-Plus#42]
I don’t consider this a problem, but more a question about SexLab and the output of animations through Pandora. Do you have a plan to do this? I saw it but didn’t understand how to use that same script. I would like to ask, will there be a full version without crutches? Oh, I also forgot to mention that @Monitor144hz is my favorite modder. Without you there would be no wonderful Pandora mod, thank you very much. And I want to congratulate you on the upcoming New Year, and wish you happiness and health, so that in 2024 you make Pandora even better, and more peace of mind for you (sorry for that situation, it was very rude)

**Comment by Monitor144hz** [comment]
Questions should be [here](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/discussions/categories/q-a) , in the discussions tab. 

To answer, I plan to add initial patch files for SL packs. _However_, that is just for the start. If the packs get updated in any way I don't have the time to maintain the patch, so that is up to the community.

**Comment by Kazyachka** [comment]
> Questions should be [here](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/discussions/categories/q-a) , in the discussions tab.
> 
> To answer, I plan to add initial patch files for SL packs. _However_, that is just for the start. If the packs get updated in any way I don't have the time to maintain the patch, so that is up to the community.

Thank you again, you're a great guy.
