### ISSUE TITLE
Magical Jump problems 

### ISSUE THREAD

**Issue by Kyationa** [Monitor144hz/Pandora-Behaviour-Engine-Plus#65]
Since updating Pandora magical jumping is activating the dash twice in one click and sends you extremely far and the jumps going up to 3 do not work making it so you only having basic jumping and that's all that happens tried resetting the mod and it still seems to cause the problem no idea what happened with it here is my Output for Pandora will try new save and see if it could be the old save.
[Pandora Output.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13815247/Pandora.Output.zip)

**Comment by Monitor144hz** [comment]
@Kyationa did you clear old output as ordered?

**Comment by Monitor144hz** [comment]
![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/89633536/607a97a0-9711-4a09-8224-b5656188c236)
Behavior file edit times are mismatched by about ~30 minutes, it looks like old files left over in directory.

**Comment by Kyationa** [comment]
When I get home I'll test again I did clear output but I will reclear and see if it happens again and I'll send a update

**Comment by Kyationa** [comment]
so cleared the output folder then tried still did not work got it to work after reinstalling the mod.

**Comment by zack0529** [comment]
> so cleared the output folder then tried still did not work got it to work after reinstalling the mod.

so it works now?

**Comment by elbadcode** [comment]
Works completely fine on all Pandora versions. Far more likely there is a dependency issue or a problem with your OAR setup that you should investigate through the in-game UI

Payload interpreter is a possible candidate for the issue here. I recommend deleting the nemesis folder for payload interpreter and using the Behavior data injector patch for it and reinstall OAR and AMR newest versions
